import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  AvatarModule,
  BadgeModule,
  BreadcrumbModule,
  ButtonGroupModule,
  ButtonModule,
  CardModule,
  DropdownModule,
  FooterModule,
  FormModule,
  GridModule,
  HeaderModule,
  ListGroupModule,
  NavModule,
  ProgressModule,
  SharedModule,
  SidebarModule,
  TabsModule,
  UtilitiesModule,
  AccordionModule,
  CarouselModule,
  CollapseModule,
  PaginationModule,
  PlaceholderModule,
  PopoverModule,
  SpinnerModule,
  TableModule,
  TooltipModule,
  ModalModule,
  AlertModule,
} from '@coreui/angular';
import { IconModule, IconSetService } from '@coreui/icons-angular';
import { LoaderComponent } from './loader/loader.component';
import { TableNodataComponent } from './table-nodata/table-nodata.component';
import { NgxSelectModule } from 'ngx-select-ex';
import { StatusComponent } from './status/status.component';
import { DataTablesModule } from 'angular-datatables';
import { BtnActionComponent } from './btn-action/btn-action.component';

@NgModule({
  declarations: [
    LoaderComponent,
    TableNodataComponent,
    StatusComponent,
    BtnActionComponent
  ],
  imports: [
    CommonModule,
    AvatarModule,
    BadgeModule,
    BreadcrumbModule,
    ButtonGroupModule,
    ButtonModule,
    CardModule,
    DropdownModule,
    FooterModule,
    FormModule,
    GridModule,
    HeaderModule,
    ListGroupModule,
    NavModule,
    ProgressModule,
    SharedModule,
    SidebarModule,
    TabsModule,
    UtilitiesModule,
    AccordionModule,
    CarouselModule,
    CollapseModule,
    PaginationModule,
    PlaceholderModule,
    PopoverModule,
    SpinnerModule,
    TableModule,
    TooltipModule,
    ModalModule,
    AlertModule,
    NgxSelectModule,
    DataTablesModule
  ],
  exports:[
    CommonModule,
    AvatarModule,
    BadgeModule,
    BreadcrumbModule,
    ButtonGroupModule,
    ButtonModule,
    CardModule,
    DropdownModule,
    FooterModule,
    FormModule,
    GridModule,
    HeaderModule,
    ListGroupModule,
    NavModule,
    ProgressModule,
    SharedModule,
    SidebarModule,
    TabsModule,
    UtilitiesModule,
    AccordionModule,
    CarouselModule,
    CollapseModule,
    PaginationModule,
    PlaceholderModule,
    PopoverModule,
    SpinnerModule,
    TableModule,
    TooltipModule,
    ModalModule,
    AlertModule,
    LoaderComponent,
    TableNodataComponent,
    NgxSelectModule,
    StatusComponent,
    DataTablesModule,
    BtnActionComponent
  ]
})
export class CoreModule { }
